In [1]:
import numpy as np

In [2]:
two_dimensional_array=[[1,2,6],[6,9,20],[65,55,20]]
matrix_1=np.array(two_dimensional_array)
print("This is your first matrix")
print(matrix_1)

This is your first matrix
[[ 1  2  6]
 [ 6  9 20]
 [65 55 20]]


In [3]:
matrix_2=np.array(two_dimensional_array)
print("This is your second matrix which is same as the first one")
print(matrix_2)

This is your second matrix which is same as the first one
[[ 1  2  6]
 [ 6  9 20]
 [65 55 20]]


In [4]:
print("And now it's time for addition of two matrcies and the result of the addition of two matrix is ")
print(matrix_1+matrix_2)

And now it's time for addition of two matrcies and the result of the addition of two matrix is 
[[  2   4  12]
 [ 12  18  40]
 [130 110  40]]


In [5]:
print("And now it's time for multiplication of two matrcies and the result of the multiplication of two matrix is ")
print(matrix_1*matrix_2)

And now it's time for multiplication of two matrcies and the result of the multiplication of two matrix is 
[[   1    4   36]
 [  36   81  400]
 [4225 3025  400]]


In [7]:
print("Now the square root of every element of your first matrix is ")
print(np.sqrt(matrix_1))

Now the square root of every element of your first matrix is 
[[1.         1.41421356 2.44948974]
 [2.44948974 3.         4.47213595]
 [8.06225775 7.41619849 4.47213595]]


In [8]:
print("And the square root of every element of your Second matrix is ")
print(np.sqrt(matrix_2))

And the square root of every element of your Second matrix is 
[[1.         1.41421356 2.44948974]
 [2.44948974 3.         4.47213595]
 [8.06225775 7.41619849 4.47213595]]


In [9]:
print(f"The summation of every element of your first matrix is {np.sum(matrix_1)}")

The summation of every element of your matrix is 184


In [12]:
print(f"The summation of every element of your second matrix is {np.sum(matrix_2)}")

The summation of every element of your second matrix is 184


In [13]:
print(f"The minimum Value from your first matrix is {matrix_1.min()}")

The minimum Value from your first matrix is 1


In [14]:
print(f"And The minimum Value from your second matrix is {matrix_2.min()}")

And The minimum Value from your second matrix is 1
