In [8]:
import numpy as np

In [9]:
numpy_array=np.array([[1,0,3],[5,90,65],[20,30,54]])
print(numpy_array)

[[ 1  0  3]
 [ 5 90 65]
 [20 30 54]]


In [10]:
print("So we founded an array index where the value is greater than 5 ",np.where(numpy_array>5))

So we founded an array index where the value is greater than 5  (array([1, 1, 2, 2, 2], dtype=int64), array([1, 2, 0, 1, 2], dtype=int64))


In [11]:
print(np.count_nonzero(numpy_array))

8


In [12]:
print(np.nonzero(numpy_array))

(array([0, 0, 1, 1, 1, 2, 2, 2], dtype=int64), array([0, 2, 0, 1, 2, 0, 1, 2], dtype=int64))
