In [2]:
import numpy as np

In [3]:
array=np.zeros((2,5))
print(array)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [4]:
print(array[0][1])

0.0


In [5]:
array_2=np.arange(10)
print(array_2)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
array_3=np.linspace(1,4,4)
print(array_3)

[1. 2. 3. 4.]


In [7]:
empty_array=np.empty([3,3])
print(empty_array)

[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 7.90505033e-321]
 [0.00000000e+000 6.79038653e-313 0.00000000e+000]]


In [8]:
Identity_Matrices=np.identity(450)
print(Identity_Matrices)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [9]:
print(Identity_Matrices.shape)

(450, 450)


In [10]:
numpy_array=np.arange(20)
print(numpy_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [12]:
numpy_array=numpy_array.reshape(2,10)
print(numpy_array)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [14]:
numpy_array=numpy_array.ravel()
print(numpy_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
