In [1]:
import numpy as np

In [2]:
list=[1,5,9,30]
one_Dimensional_array=np.array(list)
print("So this is your one dimensional array ",one_Dimensional_array)

So this is your one dimensional array  [ 1  5  9 30]


In [5]:
print(f"The maximum value from your array is placed on {one_Dimensional_array.argmax()} Index.")

The maximum value from your array is placed on 3 Index.


In [6]:
print(f"The minimum value from your array is placed on {one_Dimensional_array.argmin()} Index.")

The minimum value from your array is placed on 0 Index.


In [9]:
Two_dimensional_list=[[1,2,5],[5,6,9],[87,20,6]]
Two_dimensional_array=np.array(Two_dimensional_list)
print("So this is two dimensional array which is more of a matrices with rows and columns")
print(Two_dimensional_array)

So this is two dimensional array which is more of a matrices with rows and columns
[[ 1  2  5]
 [ 5  6  9]
 [87 20  6]]


In [11]:
print(f"So the maximum value from your two dimensional array is placed on {Two_dimensional_array.argmax()} index")

So the maximum value from your two dimensional array is placed on 6 index


In [12]:
print(f"So the minimum value from your two dimensional array is placed on {Two_dimensional_array.argmin()} index")

So the minimum value from your two dimensional array is placed on 0 index


In [15]:
print("Your matrices should be written in this order")
print(Two_dimensional_array.argsort())

Your matrices should be written in this order
[[0 1 2]
 [0 1 2]
 [2 1 0]]


In [16]:
print("The Rows Of Your matrices should be written in this order")
print(Two_dimensional_array.argsort(axis=0))

[[0 0 0]
 [1 1 2]
 [2 2 1]]


In [19]:
print("The columns Of Your matrices should be written in this order")
print(Two_dimensional_array.argsort(axis=1))

The columns Of Your matrices should be written in this order
[[0 1 2]
 [0 1 2]
 [2 1 0]]


In [21]:
sorted_array=Two_dimensional_array.argsort()
sorted_array.ravel()

array([0, 1, 2, 0, 1, 2, 2, 1, 0], dtype=int64)